import type { IconPreset } from "../context/icon-preset"

export const softIconNames = [
  "archive",
  "arrow-down-to-line",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrow-undo-down",
  "check",
  "check-small",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "checklist",
  "circle-ban-sign",
  "circle-check",
  "circle-x",
  "close",
  "close-small",
  "code",
  "code-lines",
  "copy",
  "download",
  "eye",
  "file-tree",
  "folder",
  "folder-add-left",
  "glasses",
  "github",
  "help",
  "keyboard",
  "layout-bottom",
  "layout-bottom-full",
  "layout-bottom-partial",
  "layout-left",
  "layout-left-full",
  "layout-left-partial",
  "layout-right",
  "layout-right-full",
  "layout-right-partial",
  "link",
  "magnifying-glass",
  "magnifying-glass-menu",
  "menu",
  "new-session",
  "new-session-active",
  "dot-grid",
  "plus",
  "plus-small",
  "prompt",
  "reset",
  "review",
  "review-active",
  "server",
  "settings-gear",
  "share",
  "sidebar",
  "sidebar-active",
  "sliders",
  "square-arrow-top-right",
  "status",
  "status-active",
  "stop",
  "terminal",
  "terminal-active",
  "trash",
  "warning",
  "window-cursor",
] as const

const softIconSet = new Set<string>(softIconNames)

export function shouldUseSoftIcon(preset: IconPreset, name: string) {
  return preset === "soft" && softIconSet.has(name)
}
